ArtworkAdapter.fetchandMakeArtworks()
  .then(ArtistAdapter.fetchandMakeArtists)
  .then(Artist.renderAllArtists)
  .then(RandomArtworkAdapter.fetchandMakeArtworks)
  .then(Random.renderRandomSelection)
